# Generated by Django 3.2.4 on 2024-06-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_scraper', '0003_job_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='job',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
